[package]
name = "chess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.24"
either = "1.9.0"
ron = "0.8"
serde = { version = "1.0", features = ["derive"] }
